env:
  node: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
    - avoidEscape: true
  semi: error
