version: 2.1

references:
  workspace: &workspace
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace

executors:
  node:
    docker:
      - image: circleci/node:12.14.0
    working_directory: *workspace

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - persist_to_workspace:
          root: *workspace
          paths:
            - "*"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    executor: node
    steps:
      - *attach_workspace
      - run: npm test

  deploy:
    executor: node
    steps:
      - *attach_workspace
      - run:
          name: .npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /tmp/workspace/.npmrc
      - run: npm run deploy

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: npm-publish
          requires:
            - test
          filters:
            branches:
              only:
                - master
